### PR TITLE
Fixes and funtional Q&A

### PR DESCRIPTION
**Pull request by SheriefS**
Fixed navigation although we are using two different .css files.
Added Question/answer capability
Added basic routing for some non-implemented pages
Only uploaded templates that were not in repository or modified
#11 #23

### CODE REVIEW

**Comment by mathildetq** [comment]
You can delete the class about Post and the post that are after the #, it was just an example of where your question home page would of been!

**Comment by krishnnas** [comment]
Looks good, we can merge.

**Comment by mathildetq** [comment]
All good!

**Review by krishnnas — APPROVED** [review]
approved.

**Pull request merged**
