### PR TITLE
Implemented vote button limitations

### PR DESCRIPTION
**Pull request by SheriefS**
This code only allows a user to vote on a question once.  No changes were made to the html files, so buttons are still visible. Fixes bug in #62 and a user will now only be able to vote once. We may still want to make a visual representation to a user that they have already voted.

### CODE REVIEW

**Comment by SheriefS** [comment]
Ok found a pretty big bug, going to need to fix it first. The voting stops everywhere

**Comment by Arsollo** [comment]
Closes #62

**Review by Arsollo — APPROVED** [review]

**Comment by Arsollo** [comment]
Added CSS visual representation for user to see if they already voted

**Review by krishnnas — APPROVED** [review]
looks good

**Review by mathildetq — APPROVED** [review]
This works well, you can merge

**Pull request merged**
